# Generated by Django 4.0.4 on 2022-05-18 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.TextField()),
                ('location', models.TextField()),
                ('menu', models.TextField()),
                ('weather', models.TextField()),
                ('song', models.TextField()),
                ('point', models.IntegerField()),
                ('content', models.TextField()),
                ('image', models.ImageField(default='media/coffee_default.jpg', upload_to='media/')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('liked', models.BooleanField(default=False)),
                ('num_liked', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
